name: Amity
main: com.GuyInGrey.Amity.Amity
version: 1.0
api-version: 1.13
depend: [NoteBlockAPI, DiscordSRV]
commands:
  lobby:
    description: Teleports you to the lobby.
    usage: /lobby
  maze:
    description: Makes a maze.
    usage: /maze
  cellborder:
    description: Shows cell borders.
    usage: /cellborder
  pack:
    description: Gives you the resource pack.
    usage: /pack
  dungeon:
    description: Dungeon
    usage: /dungeon